# Generated by Django 4.0.4 on 2022-05-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='账号')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='邮箱')),
                ('ip', models.CharField(default='127.0.0.1', max_length=20, verbose_name='上次访问ip地址')),
                ('login_date', models.DateTimeField(verbose_name='上次登录时间')),
            ],
        ),
    ]
