# Generated by Django 4.0.4 on 2022-05-30 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 30, 8, 13, 25, 883751), verbose_name='dfs'),
        ),
    ]
