# Generated by Django 4.0.4 on 2022-05-30 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_alter_user_test_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='test_date',
        ),
    ]
