# Generated by Django 4.0.4 on 2022-05-30 08:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_remove_user_test_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='上次登录时间'),
        ),
    ]
