# Generated by Django 4.0.4 on 2022-05-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_alter_user_login_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_date',
            field=models.DateTimeField(verbose_name='上次登录时间'),
        ),
    ]
