# Generated by Django 4.0.4 on 2022-06-06 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='password',
            old_name='user_id',
            new_name='user',
        ),
    ]
